name: Workflow for example-clojure
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0-beta
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Run tests
        run: lein test
      - name: Cloverage
        run: CLOVERAGE_VERSION=1.1.1 lein cloverage --codecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5.0.0-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
        with:
          file: target/coverage/codecov.json
