name: Workflow for example-clojure
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Run tests
        run: lein test
      - name: Cloverage
        run: CLOVERAGE_VERSION=1.1.1 lein cloverage --codecov
      - name: Upload to Codecov (Action)
        uses: codecov/codecov-action@v2
        with:
          file: target/coverage/codecov.json
      - name: Upload to Codecov (Uploader)
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f target/coverage/codecov.json
